server:
  port: 8383

spring:
  main:
    allow-bean-definition-overriding: true


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sundo23501a
    username: postgres
    password: tiger
  