server:
  port: 8383

spring:
  main:
    allow-bean-definition-overriding: true


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sundo23501a
    username: postgres
    password: tiger
  #gmail transfer
  mail:
    host: smtp.gmail.com
    port: 587
    username: jinijuniwa@gmail.com
    password: vctdpmxycqugxznr
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
